export const PATH = {
  MAIN: '/',
  LOGIN: '/login',
  COIN: '/coin',
  LOGINOAUTH: '/oauth',
  SIGNUP: '/signup',
  MYPAGE: '/mypage',
  COLLECTION: '/collection',
  ITEM: '/item',
  STORE: '/store',
  CREATE_BOUQUET: '/create-bouquet',
  PURCHASE: '/store/purchase',
  WRITE: '/write',
  DECORATE_BOUQUET: '/decorate-bouquet',
}
