export { default as MainPage } from './MainPage'
export { default as LoginPage } from './LoginPage'
export { default as MyPage } from './MyPage'
export { default as CoinDrawPage } from './CoinDrawPage'
export { default as OauthPage } from './OauthPage'
