export { default as WrapperWhiteBackImage } from './wrapper_white_back.svg?react'
export { default as WrapperWhiteFrontLeftImage } from './wrapper_white_front_left.svg?react'
export { default as WrapperWhiteFrontRightImage } from './wrapper_white_front_right.svg?react'
export { default as WrapperWhiteItem } from './wrapper_white_item.svg?react'
export { default as WrapperBlackBackImage } from './wrapper_black_back.svg?react'
export { default as WrapperBlackItem } from './wrapper_black_item.svg?react'
export { default as WrapperBlackFrontLeftImage } from './wrapper_black_front_left.svg?react'
export { default as WrapperBlackFrontRightImage } from './wrapper_black_front_right.svg?react'
